name: 'Ghost Digest Generator'
description: 'Generate daily or weekly digests for Ghost blogs'
branding:
  icon: 'mail'
  color: 'green'
inputs:
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'
  url:
    description: 'URL of the Ghost blog'
    required: true
  period:
    description: 'Digest period (daily or weekly)'
    required: true
    default: 'daily'
  tags:
    description: 'Comma-separated list of tags for the digest post'
    required: false
    default: 'Digest'
  excluded_tags:
    description: 'Comma separated list of tags; if a post has any of these tags, it will not be included'
    required: false
    default: ''
  title:
    description: 'Title of the digest post'
    required: false
  timezone:
    description: 'Timezone to use for date calculations'
    required: false
    default: 'America/Chicago'
  full_article:
    description: 'Include full article content in the digest post'
    required: false
    default: 'false'
outputs:
  result:
    description: 'The result of the digest generation'
runs:
  using: 'node20'
  main: 'dist/index.ts'
